### ISSUE TITLE
Minimum Viable Product (MVP) Roadmap

### ISSUE THREAD

**Issue by wgtmac** [apache/iceberg-cpp#2]
Below are planned roadmap for MVP as discussed in different places (e.g. dev ML, Github issues & PRs, slack channel, etc.). Note that it is only for the native C++ implementation. For the effort of Rust C++ binding, please refer to https://lists.apache.org/thread/hotlcdw86nrmt7cf5o5o7kq6gwo98758.

# Convention

- Platform: Linux, MacOS, Windows
- Compilers: Clang, GCC, MSVC
- Build: CMake
- C++ standard: C++23
- Coding style: Follow what Apache Arrow C++ does: https://arrow.apache.org/docs/developers/cpp/development.html#code-style-linting-and-ci
- Error handling: use ported `expected` similar to `std::expected`

# Goal

- Implement read path for parsing metadata files of Iceberg v1 & v2. It is a nice-to-have feature to read data files depending on the bandwidth of contributors.
- Provide a light-weight io-less `iceberg` library with minimal dependencies (like `apache/nanoarrow` and `nlohmann/json`) to mainly deal with the Iceberg metadata. Downstream projects are required to provide their own implementations like I/O, Parquet, Avro and write adaptation code.
- Provide a battery-included `iceberg-bundle` library backed by Apache Arrow C++ and Apache Avro C++ libraries.

# Workitems

(Disclaimer: this is not an exhaustive list and is subject to change as the development goes on)

## API of metadata or building block

- [x] Add `Schema` (including data types)
- [x] Add `DataFile`
~~- [ ] Add `DeleteFile`~~
- [x] Add `ManifestFile`
- [x] Add `ManifestEntry`
- [x] Add `Snapshot`
- [x] Add `PartitionSpec`
- [x] Add `SortOrder`
- [x] Add `ManifestList`
- [x] Add `TableMetadata`

## Catalog

- [x] Define `Catalog` interface.
- [x] Implement an in-memory catalog.

## IO

- [x] Define `FileIO` interface with minimal operations.
- [x] Provide default FileIO implementation backed by `arrow::FileSystem` for different storage providers.

## Table

- [x] Define `Table` interface.
- [x] Provide a basic Table implementation to have access to its metadata. @lishuxu
- [x] Implement `Table::NewScan` function and `TableScan` class to support planning files for reading a specific snapshot. @gty404
- [ ] Implement partition pruning and data file pruning in the `TableScan`. (Postponed to 0.2.0)

## JSON Serialization

- [x] SortOrder
- [x] PartitionSpec
- [x] Schema
- [x] Snapshot
- [x] TableMetadata
- [x] NameMapping

## Metadata File Reader

- [x] JSON file reader.
- [x] JSON parser for metadata objects.
- [x] Reading gzip-compressed metadata json file.

## File Format Reader

- [x] Define format-agnostic `FileReader` interface with Arrow C Data as the contract.
- [x] Implement manifest list file reader. @dongxiao1198 
- [x] Implement manifest file reader.
- [x] Provide default Avro reader implementation in the `iceberg-bundle` library.
- [x] Provide default Parquet reader implementation in the `iceberg-bundle` library.

## Schema/Data conversion

- [x] Bi-directional conversion to Arrow C schema.
- [x] ArrowArray -> avro::GenericDatum
- [x] avro::GenericDatum -> ArrowArray

## Expression
- [x] Transform metadata
- [x] Transform function
- [ ] Expression components: expression, term, literal, reference, etc. https://github.com/apache/iceberg-cpp/pull/177
- [ ] Expression visitor (Postponed to 0.2.0)

## Third-party library

- [x] Add `nanoarrow` to `libiceberg`
- [x] Add `nlohmann/json` to `libiceberg` @yingcai-cy
- [x] Add `avro-cpp` to `libiceberg-bundle`
- [x] Add `arrow-cpp` to `libiceberg-bundle`

## First release

- [ ] Check licenses.
- [ ] Check documentations.
- [ ] Add release script.

**Comment by wgtmac** [comment]
I have made a bold suggestion that the type system to directly leverage Arrow C++ to avoid re-invent the wheels and benefit from RecordBatch, Expression and other stuff. I saw that iceberg-rust and iceberg-go have implemented its own data types. Is there any issue that arrow type system is unable to deal with iceberg type system? @Xuanwo @zeroshade

**Comment by wgtmac** [comment]
Thanks @zeroshade for the detail! 

The table below is the type mapping between iceberg and arrow. I think we can provide a wrapper around arrow data types to use only a subset of them. On the read path, the mapping is pretty clear except for String/LargeString/Binary/LargeBinary. We can by default use String/Binary unless explicitly configured. On the write path, we can simply error out for unsupported arrow types. Just want to add that the ongoing iceberg `variant` and `geometry` types will not have any issue, parquet-cpp will anyway implement them because they are part of the parquet spec. Therefore I don't think there is a compelling reason not to use `arrow::DataType` directly.

| iceberg | arrow |
|---------|-------|
| unknown | Null  |
| boolean | Boolean |
| int     | Int32  |
| long    | Int64  |
| float   | Float32 |
| double  | Float64 |
| decimal(P,S) | Decimal(P,S) |
| date    | Date32 |
| time    | Time64 |
| timestamp | Timestamp(MICRO) |
| timestamptz | Timestamp(MICRO,UTC) |
| timestamp_ns | Timestamp(NANO) |
| timestamptz_ns | Timestamp(NANO,UTC) |
| string  | String/LargeString |
| uuid    | UUID canonical extension type |
| fixed(L) | FixedSizeBinary (L) |
| binary  | Binary/LargeBinary |
| struct  | Struct |
| list    | List/LargeList |
| map     | Map |

**Comment by zeroshade** [comment]
For Arrow decimal types you'll need to specify which decimal type to use, I recommend using 128-bit because that's the max supported by iceberg. 

For the geometry type, you can use the GeoArrow community extension types.

There is also a proposal to add the variant type to Arrow also after it is accepted into parquet, so that should work out fine too.

**Comment by wgtmac** [comment]
Agreed, in essence this is pretty much the same question to parquet-cpp on what is the best arrow data type to use for a specific parquet (iceberg) type.

**Comment by wgtmac** [comment]
Thanks @Fokko for the reply!

> I would also lean towards having a separate type system.

I agree that the efficiency of field-id and inability to set default value make arrow schema not that appealing. I think the problem is `arrow::Field` not `arrow::DataType`. What about creating yet another `iceberg::Field` to wrap `arrow::DataType` with better support of iceberg concepts? In this way, the type visitors of arrow-cpp still work and so do arrow::Expression and arrow::Scalar. @Fokko @zeroshade 

> I think we can wrap the arrow::FileSystem within a FileIO

Yes, it is exactly what's in my mind.

> people could even provide their own FileIO through configuration if they like.

This might be challenging since we don't have an easy approach to use reflection in C++.

**Comment by boroknagyz** [comment]
> > people could even provide their own FileIO through configuration if they like.

> This might be challenging since we don't have an easy approach to use reflection in C++.

I think we just need a plugin mechanism to allow that, no need for reflection. If we have a clear interface of a FileIO, it shouldn't be too hard to make things pluggable.
It can be important for S3, as some implementations (e.g. Hadoop's S3AFileSystem) use s3a:// prefixes, while others use s3:// prefixes.

+1 on having a separate type system for better control and simplicity.

**Comment by Fokko** [comment]
> What about creating yet another `iceberg::Field` to wrap `arrow::DataType` with better support of iceberg concepts?

I think it should then wrap a `arrow: Field`, otherwise we would not be able to pass it into a [`arrow::Struct`](https://arrow.apache.org/docs/python/generated/pyarrow.struct.html). But now the struct returns `arrow:Field`, so then we should create a `iceberg::Struct` as well, otherwise we're casting all over the place. My biggest concern is that we have code all over the place to coerce the Arrow superset into the Iceberg types. To me, the Arrow system mixes both how it is encoded (`large_`) and the actual types, while a `Decimal` in Iceberg [should be encoded](https://github.com/apache/iceberg/blob/main/format/spec.md#parquet) as a `int32` when `P <= 9`.

> If we have a clear interface of a FileIO, it shouldn't be too hard to make things pluggable.

That's exactly what I meant, thanks for clarifying :)

**Comment by pitrou** [comment]
> * Dependencies: [Arrow](https://github.com/apache/arrow), [Avro](https://github.com/apache/avro), [ORC](https://github.com/apache/orc), [simdjson](https://github.com/simdjson/simdjson), etc.

Dependency management in Arrow C++ has been a huge headache (and still is). I'd heavily recommend that Iceberg C++ starts with a minimal set of dependencies. I don't know what ORC or Avro has to do with it, for example.

Arrow C++ is certainly a requirement; it will give access to useful base features (IO etc.), and of course to Parquet C++ APIs.

simdjson seems reasonable as well, and a JSON library is very useful for a bunch of tasks (such as writing nice testing helpers or CLI utilities).

**Comment by lidavidm** [comment]
I would almost rather not depend on Arrow C++ if possible (what if I want to use the cuDF parquet reader, or OpenDAL for S3 access?)

**Comment by wgtmac** [comment]
> I would almost rather not depend on Arrow C++ if possible

AFAIK, Arrow C++ includes the most complete implementation of Parquet reader and writer. In addition, arrow columnar format seems to be the best choice to be integrated with other engines. We can 
@lidavidm Great question!

> what if I want to use the cuDF parquet reader, or OpenDAL for S3 access?

We should design a good interface for file reader and writer so we get the chance to plugin different parquet implementations. Similarly a good `FileIO` abstraction does not block us to choose S3 access from Arrow FileSystem or OpenDAL implementation. Perhaps @etseidl and @Xuanwo could chime in for cuDF and OpenDAL respectively.

**Comment by lidavidm** [comment]
I suppose as long as it's possible to drop all the I/O parts (and ideally dependencies) and try to use the library purely to parse Iceberg snapshots/manifests etc, that would work for my purposes (which is to integrate Iceberg into other projects, so having the library perform I/O itself is actually undesirable)

**Comment by lidavidm** [comment]
FWIW, nanoarrow means we can use the format itself without having to take every single dependency (though if the plan is to require the Arrow C++ readers, compute functions, etc. then I suppose there's no choice there)

**Comment by wgtmac** [comment]
For your use case, I think we can provide a `iceberg-lite` or `iceberg-core` library:
- Define extensible interfaces for I/O and file reader/writers.
- Only depend on nanoarrow to leverage arrow columnar layout for reading/writing data.

By default, a `iceberg-arrow` library could provide concrete implementations of those interfaces by leveraging filesystem and parquet reader/writer from arrow cpp. WDYT? @lidavidm

**Comment by lidavidm** [comment]
If that's possible that would be much appreciated. Though I can understand not wanting to deal with that in C++, or taking the dependency but at least leaving the core logic reusable somehow.

That said either way I'm interested in helping here, given I'm working on an Iceberg reader in any case.

**Comment by pitrou** [comment]
> I suppose as long as it's possible to drop all the I/O parts (and ideally dependencies) and try to use the library purely to parse Iceberg snapshots/manifests etc, that would work for my purposes (which is to integrate Iceberg into other projects, so having the library perform I/O itself is actually undesirable)

I think this is definitely a worthwhile goal.

**Comment by Fokko** [comment]
I agree with what's been said before about keeping the set of dependencies as low as possible. Would it be possible to define the [`FileIO` interface](https://github.com/apache/iceberg/blob/main/api/src/main/java/org/apache/iceberg/io/FileIO.java) and let the dependent sub-project implement this (and have one implementation in tests of course)? The FileIO is [a pretty opinionated part](https://www.tabular.io/blog/iceberg-fileio-cloud-native-tables/) of Icebergs' design. During the query-planning process, Iceberg needs to be able to fetch manifests based on the evaluation of the metadata. Keep also in mind, that in Iceberg, the catalog often uses credential vending, where it will pass [certain properties](https://github.com/apache/iceberg/blob/38c8daa4eae8a75ab46571f1efce1609100f53dd/open-api/rest-catalog-open-api.yaml#L3193) to the `FileIO` to set credentials.

**Comment by pitrou** [comment]
Another possibility perhaps would be an IO-less abstraction (the Iceberg library tells you what it is waiting for, and you give it what it asks for). Probably more complex to design (and you still perhaps want convenience libraries on top), but definitely more flexible.

**Comment by Fokko** [comment]
> you don't want everyone to reimplement the same thing

Yes, that's also my concern. I don't know if you can make this modular in C++, similar to Java/Python.

> Another possibility perhaps would be an IO-less abstraction (the Iceberg library tells you what it is waiting for, and you give it what it asks for). Probably more complex to design (and you still perhaps want convenience libraries on top), but definitely more flexible.

That would work as well. The FileIO is designed to avoid certain operations (move/list/etc), and it only does a few things (read, create, and delete). If wrap this into an abstraction, that would work just as well.

**Comment by wgtmac** [comment]
> The FileIO is designed to avoid certain operations (move/list/etc), and it only does a few things (read, create, and delete). If wrap this into an abstraction, that would work just as well.

I plan to do the following PoC as the next step:
- Define `FileIO` related abstraction in the `iceberg-core` library.
- Add a `iceberg-arrow` library to provide concrete implementation of `FileIO` backed by `arrow::FileSystem`. This requires to add Arrow as a third-party library. I can use a CMake option `ICEBERG_USE_ARROW` to make it optional.

> Another possibility perhaps would be an IO-less abstraction (the Iceberg library tells you what it is waiting for, and you give it what it asks for). Probably more complex to design (and you still perhaps want convenience libraries on top), but definitely more flexible.

I'd like to hear more of this. Perhaps a naive example to demonstrate it?

**Comment by lidavidm** [comment]
> Another possibility perhaps would be an IO-less abstraction (the Iceberg library tells you what it is waiting for, and you give it what it asks for). Probably more complex to design (and you still perhaps want convenience libraries on top), but definitely more flexible.

I've long thought a big failing of parquet-cpp is that it _isn't_ architected like this. It's caused me a lot of pain across multiple companies.

**Comment by pitrou** [comment]
> I'd like to hear more of this. Perhaps a naive example to demonstrate it?

I was thinking something like this. But I'm not an Iceberg expert at all.
```c++
struct FileOpenRequest {
  std::string path;
  FileInfo info;
};

struct FileOpenResult {
  std::any file_handle;
};

struct ReadRangeRequest {
  std::any file_handle;  // corresponds to FileOpenRequest::file_handle
  int64_t offset, length;
};

struct ReadRangeResult {
  std::shared_ptr<Buffer> data;
};

struct IoRequest {
  std::any handle;
  std::variant<FileOpenRequest, ReadRangeRequest> op;
};

struct IoResult {
  std::any handle;  // corresponds to IoRequest::handle
  std::variant<FileOpenResult, ReadRangeResult> op;
};

class IcebergReader {
 public:
  // Ask the reader which IOs are needed to move forward
  std::vector<IoRequest> NeedIo();
  // Instruct the reader about these IO results
  void IoReceived(std::vector<IoResult>);

  // Optional - IOs which may be needed in the future
  std::vector<IoRequest> SpeculatedIo();
};
```

**Comment by GregoryKimball** [comment]
Thank you for this discussion.

> I would almost rather not depend on Arrow C++ if possible (what if I want to use the cuDF parquet reader, or OpenDAL for S3 access?)

From the cuDF side, we are happy users of `nanoarrow` and dropping our libarrow dependency in 24.08 has helped our partners. We would love a lightweight iceberg IO tool to add to our [KvikIO library](https://github.com/rapidsai/kvikio/blob/branch-25.02/cpp/include/kvikio/remote_handle.hpp). We recently added S3 support via `libcurl` and would like to expand support for other object stores.

It's unlikely that we would take up a libarrow dependency via `iceberg-arrow` if we could use `iceberg-core` to handle the basic IO needs.

**Comment by wgtmac** [comment]
Thanks @GregoryKimball for the input! I think `iceberg-core` should only contain a clean I/O interface (like `RemoteHandle` in your provided example) with a default implementation for local filesystem. Depending on `libcurl` to implement access to cloud object stores (perhaps in a separate `libiceberg-io` library) is a good option compared to managing disparate C++ SDKs from cloud vendors (which is painful in Apache Arrow). In this way, downstream projects (like KvikIO) can adapt their own I/O implementation to it. 

cc @MisterRaindrop who has expressed an interest in HDFS implementation.

**Comment by MisterRaindrop** [comment]
@GregoryKimball 
I am also interested in accessing different cloud providers through libcurl. We can implement the corresponding interfaces based on libcurl. Different cloud providers can achieve high-speed access to object storage by defining their own specific interfaces.

**Comment by MisterRaindrop** [comment]
Due to the heavy reliance on Arrow, does Iceberg-cpp have plans to provide an abstract interface to allow integration with one’s own Parquet, Avro, etc., libraries without depending on Arrow?

**Comment by lidavidm** [comment]
@MisterRaindrop the earlier discussion in this thread is about exactly that topic - the plan is to have iceberg-core and a separate iceberg-arrow

**Comment by MisterRaindrop** [comment]
Is it possible to allow users to customize and choose their own parser (like options) or use Arrow for parsing? 
Because I want a cleaner dependency.

**Comment by MisterRaindrop** [comment]
@wgtmac I’m quite curious. I only saw the reading part. Will there be writing designs?

**Comment by wgtmac** [comment]
> Is it possible to allow users to customize and choose their own parser (like options) or use Arrow for parsing?
Because I want a cleaner dependency.

You mean the JSON parser? I'm not sure if we want to make it pluggable. For the `libiceberg-core`, I think we need to depend on https://github.com/apache/arrow-nanoarrow and https://github.com/simdjson/simdjson as the minimum dependencies. `nanoarrow` is required to leverage the columnar layout for data exchange. `simdjson` is used to parse json and convert to the Arrow format. Perhaps we can design interface for the JSON parser and add an extra `libiceberg-simdjson` to plugin a default json implementation if that meets your requirement?

> I only saw the reading part. Will there be writing designs?

This is the MVP goal. Writing is absolutely on the roadmap but I don't think we have time to include it in the MVP.

**Comment by MisterRaindrop** [comment]
A little immature idea!  
The current implementation of Iceberg I am not use Arrow at all. I am currently reading data directly through Parquet, Avro, etc. I would like to have a certain degree of flexibility, ideally allowing users like me to customize the dependencies they need.

**Comment by wgtmac** [comment]
It might be a good time to create a PR to prototype a `FileReader` interface for Json/Parquet/Avro. Unfortunately I don't have time this week (and perhaps next week).

> The current implementation of Iceberg I am not use Arrow at all.

Just curious what is your current data exchange protocol? Is it the row-wise or columnar data layout specific to your engine? I prefer Arrow because it is the de facto standard.

**Comment by lidavidm** [comment]
You could imagine a core library that only does planning/parsing, and doesn't return data at all, though. (Just: read these data files, apply these delete files, etc.)

**Comment by MisterRaindrop** [comment]
Actually parquet as a storage format, doesn’t change frequently. Therefore I split parquet from arrow. To make it cleaner.

**Comment by mapleFU** [comment]
> > I'd like to hear more of this. Perhaps a naive example to demonstrate it?
> 
> I was thinking something like this. But I'm not an Iceberg expert at all.

How to implement something like a Parquet Page Reader or specified file reader in this scenerio? I think this might works well on visiting the iceberg manifest but I've no idea how this could live with parquet / large avro reader 🤔

**Comment by wgtmac** [comment]
0.1.0 has been released: https://github.com/apache/iceberg-cpp/releases/tag/v0.1.0.
